### ISSUE TITLE
win11 22h2系统 无法工作

### ISSUE THREAD

**Issue by Makemonkey** [RipplePiam/MobaXterm-Chinese-Simplified#12]
在新安装的win11 22h2系统上，提示“此应用无法在你的电脑上运行，若要找到使用与你的电脑的版本，请咨询软件发布者”。

**Comment by RipplePiam** [comment]
从官网下载原版的安装包，
如果也不能正常使用，大概率是兼容性问题，或者新安装电脑哪里的安全配置所致。具体要看看网上解决方案，这里不作参考；
如果官网版本能正常使用，才有可能是此汉化版的问题
附：Win11 21H2 测试是可以正常使用的。

**Comment by Makemonkey** [comment]
> 从官网下载原版的安装包， 如果也不能正常使用，大概率是兼容性问题，或者新安装电脑哪里的安全配置所致。具体要看看网上解决方案，这里不作参考； 如果官网版本能正常使用，才有可能是此汉化版的问题 附：Win11 21H2 测试是可以正常使用的。

是在官网下载的安装包，系统也是微软官网下载的，后面用了上一个版本的文件，可以正常运行，应该是新版本不兼容的问题

**Comment by RipplePiam** [comment]
> > 从官网下载原版的安装包， 如果也不能正常使用，大概率是兼容性问题，或者新安装电脑哪里的安全配置所致。具体要看看网上解决方案，这里不作参考； 如果官网版本能正常使用，才有可能是此汉化版的问题 附：Win11 21H2 测试是可以正常使用的。
> 
> 
> 
> 是在官网下载的安装包，系统也是微软官网下载的，后面用了上一个版本的文件，可以正常运行，应该是新版本不兼容的问题

👌，感谢分享🎉

**Comment by Azhc** [comment]
一样的系统版本。官方的可以正常打开，发布的两个版本试了都是这个提示

**Comment by RipplePiam** [comment]
> 后面用了上一个版本的文件，可以正常运行，应该是新版本不兼容的问题

@Azhc : 官网版本是 22.2， 已经修复此问题。
当前汉化版是 22.1。
22.2 其实也汉化了，但是用的新汉化软件与方法，效果不太满意，因此没发布。
若有需要可等待时日。
祝好。
