### ISSUE TITLE
已汉化的中文字体问题

### ISSUE THREAD

**Issue by WeiMeng22** [RipplePiam/MobaXterm-Chinese-Simplified#14]
菜单栏字体看着比较舒服，但是按钮栏的字体就不是很好了，还有侧边栏中的中文字体，好像都没有用cleartype文本，看着挺难受的，能把全局中文字体搞好看点么，大佬

**Comment by RipplePiam** [comment]
Hi, 感谢提问。
你问的是最左侧这个按钮字体吗：
![1](https://user-images.githubusercontent.com/45916506/198071137-b62c177a-56a1-4b23-8aa0-bfbf3eea6614.jpg)

答复：
如上图右侧标记 125%，表示 Windows 屏幕缩放比例。
最左侧这个字体，如果屏幕缩放比例在 100% 时，看起来是不是正常了：
![3](https://user-images.githubusercontent.com/45916506/198071604-883987ba-ff55-4975-899b-4e900d11722d.jpg)

因此这个问题不会被修复。
通常使用台式机时屏幕缩放 100% 看起来是正常的。笔记本屏幕缩放大于 100% 看起来不太好。
如果你在笔记本上使用，又不想看这个比例失调的字体，可以尝试隐藏：
![2](https://user-images.githubusercontent.com/45916506/198072250-12f2bfee-a513-4b6e-820f-31da189452dc.jpg)

关于没有使用 cleartype 字体，一是版权问题，二是软件内置字体由 https://dejavu-fonts.org/ 提供 (帮助》关于 有说明)。
因此字体不会去替换。
祝好

**Comment by WeiMeng22** [comment]
我用的笔记本，高分屏，缩放使用的是自定义的124%，我刚刚试了125%和100%，情况并没有好很多，字体看着确实不太舒服，如果不便替换那就算了，希望官方原版早日提供多语言版本，总之，感谢辛苦汉化。
