### ISSUE TITLE
现在22.2已经出了，汉化版是否会更新呢？

### ISSUE THREAD

**Issue by z4668640** [RipplePiam/MobaXterm-Chinese-Simplified#20]
https://mobaxterm.mobatek.net/download-home-edition.html
如上所示22.2已经出了。

**Comment by Guoyuh78** [comment]
路过 期待汉化

**Comment by TheBlindM** [comment]
国产T-Shell 😁https://github.com/TheBlindM/T-Shell

**Comment by dupeng0811** [comment]
> 在做了（新建文件夹 ：D

@RipplePiam  看来要改一下文件夹的名称了，12.12出了22.3版本了  ：D

**Comment by z4668640** [comment]
> > @RipplePiam  看来要改一下文件夹的名称了，12.12出了22.3版本了  ：D
> 
> 看来还是要找个快速些，又能保证质量的汉化方法。 22.2其实已经汉化差不多了，但是用的别的方法，感觉成品不满意，没放出来。

我教你个方法。Ctrl+H “22.2” “22.3”效果非常完美。：D

**Comment by zhanun** [comment]
来支持一下，期待22.3汉化的发布！！

**Comment by cyxnzb** [comment]
同样期待

**Comment by Crazyboyjw** [comment]
期待新版本

**Comment by wuxianggujun** [comment]
在百度可以搜索到mobaxterm.info，我发现他的软件比你的多出了10MB的大小。而且360可以检测出病毒

**Comment by wuxianggujun** [comment]
还好我是先看你的文章，不然就gg了

**Comment by z4668640** [comment]
我看到了22.3的文件夹。。这是做好了么？是不是忘发布了？

**Comment by cyxnzb** [comment]
> 我看到了22.3的文件夹。。这是做好了么？是不是忘发布了？

没hack

**Comment by lvbibir** [comment]
23.0版本也出了

**Comment by Jayucrol** [comment]
支持喵，已🌟感谢作者

**Comment by WoChen5770** [comment]
> 

https://www.secrss.com/articles/50209

**Comment by WoChen5770** [comment]
> 在百度可以搜索到mobaxterm.info，我发现他的软件比你的多出了10MB的大小。而且360可以检测出病毒

https://www.secrss.com/articles/50209

**Comment by RipplePiam** [comment]
转向新版本 v23.0
