### ISSUE TITLE
local terminal 中文乱码，英文显示正常。

### ISSUE THREAD

**Issue by epodak** [RipplePiam/MobaXterm-Chinese-Simplified#39]
我已经将字符集改成了黑体
Font charset: DEFAULT (System) /gb2312
Term charset: UTF-8 (Unicode) 
这样设置都无济于事。
远程ssh中文是正常显示的。
这个可能和汉化没关系。。如果好心人看到就告诉我一生。

**Comment by RipplePiam** [comment]
提 Issue 请提交截图等信息

**Comment by epodak** [comment]
![image](https://user-images.githubusercontent.com/5253044/235283470-e3301060-a94f-493b-a26f-6319dc50bcb5.png)
![image](https://user-images.githubusercontent.com/5253044/235283486-81ac27c7-52d6-4901-b124-f7d4ca689ef6.png)

**Comment by epodak** [comment]
我感觉应该是本地的类似CSS一样的东西在作怪。
我在远程ssh,这个显示是没问题的。

**Comment by epodak** [comment]
选择GBK解决了，我的AI一直让我选择UTF-8误导我。

**Comment by epodak** [comment]
GBK也没完全解决，大一统的解决方法还得是UTF-8，不过现在能用。等着大佬来解决吧。搜了一下，这好像是个普遍现象。

**Comment by RipplePiam** [comment]
> GBK也没完全解决，大一统的解决方法还得是UTF-8，不过现在能用。等着大佬来解决吧。搜了一下，这好像是个普遍现象。

MobaXterm 几个与字符集有关的默认设置：

![1](https://user-images.githubusercontent.com/45916506/235333110-75f6b2f5-ad14-44d6-a14f-b77b2a4ab0ab.png)

![2](https://user-images.githubusercontent.com/45916506/235333111-608a3eae-81f8-43dd-b108-e40a6df960c8.png)

![3](https://user-images.githubusercontent.com/45916506/235333112-89a12fd6-1b75-4e9c-88b9-de6b03645c6b.png)

日常会显示中文的会话，默认设置里的 Unicode 是可以覆盖的，没遇到过乱码的情况。
你这个问题大概率是你用的那个工具的问题

**Comment by RipplePiam** [comment]
还有一种可能是你选的黑体的问题
