### ISSUE TITLE
23版本ssh虚拟主机会非常慢

### ISSUE THREAD

**Issue by goddnessheb** [RipplePiam/MobaXterm-Chinese-Simplified#40]
最新的23版本ssh主机要等好一会儿，20版本正常

**Comment by RipplePiam** [comment]
与汉化无关。
ssh 会话中有和连接速度有关的设置：
![1](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/45916506/1fb4b359-6223-4a98-b62c-d6ff81cd98f0)
