### ISSUE TITLE
作者你好  这一部分可以进行汉化吗？对于英文不好的我 看起来很吃力

### ISSUE THREAD

**Issue by fengbo1029** [RipplePiam/MobaXterm-Chinese-Simplified#42]
![image](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/99636954/1ccadfe1-d93e-4baa-80db-d4152d1af345)

这个页面如果可以汉化就好了  对于英文不好的我 看起啦费劲

**Comment by RipplePiam** [comment]
如 #34 提 Issue 须知 中所说，右键菜单的内容，不同终端还不一样，但都是内部代码写死的，暂不会去汉化。
