### ISSUE TITLE
关于汉化的更新方式

### ISSUE THREAD

**Issue by richardodliu** [RipplePiam/MobaXterm-Chinese-Simplified#44]
感谢您对CN生态的贡献。
我这边有一个小小的建议，就是您是否考虑在以后的更新中，将汉化方式改为修改Mobaxterm软件安装地址下配置文件的方式（例如：clash客户端汉化的采用的修改.js文件的方式），而不是重新上传整个压缩文件。
个人感觉这样的更新方式可能会适当减少您的工作量，并且提高汉化的实用性，仅作为个人建议供您参考。

**Comment by Elititode** [comment]
有道理

**Comment by RipplePiam** [comment]
感谢提供建议🙏
马克先

**Comment by Jiang-Lei-CN** [comment]
> 感谢提供建议🙏 马克先

Looking forward to your latest Chinese plug-in！

**Comment by RipplePiam** [comment]
经研究，目标项目的更新方式暂不具备参考性，感谢关注与支持。
