### ISSUE TITLE
关于设备是GB2312字符集时出现乱码的问题

### ISSUE THREAD

**Issue by luancao** [RipplePiam/MobaXterm-Chinese-Simplified#45]
![image](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/25533498/514c9a52-6b1f-4136-962d-99028cfcdb8c)
你好，我使用的是你最新发布的V23.0版本，如图所示，我在终端设置里的字体设置里面，把字符集改成了使用字体编码，但是进入GB2312设备时，仍旧出现乱码。然后我右键-》Change terminal settings...-》windows-》Translation里面的Remote character set，这里的设置仍旧还是UTF8，只有这里改成最下面的Use font encoding后，才会变成中文。我试了官网最新的23.2版本，没有这个问题。不知是不是一个bug，麻烦有空的时候可以看看能否修复。另外你的中文版的确不错。目前就发现了这个问题。
对了另外，
![image](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/25533498/0c65326f-3701-4821-84bd-eb709c19e052)
官方版本23.2，改成ISO-8859-1(West Europe）也可以正常显示中文，但是你的版本，就算改成了这个，也是乱码。

**Comment by SD304** [comment]
对啊，GB2312问题怎么解决，我的串口通信单片机GB2312编码的字符显示不了，改的乱七八糟的，什么都没用

**Comment by RipplePiam** [comment]
编码问题和软件汉化无关联性。感谢关注
