### ISSUE TITLE
ssh窗口的交互是错的

### ISSUE THREAD

**Issue by OrdinaryChen** [RipplePiam/MobaXterm-Chinese-Simplified#48]
我创建了一个ssh连接  但是我在ssh里输入的命令conda显示我没有安装conda，但是我直接在远程主机上输入conda就是正常的显示安装好了的。输入python命令也是，似乎我在和另外一个她自己的系统在交互，打开ssh上方显示一个关于wsl2的ubuntu，我似乎在和这个虚拟机交互，如图，我输入conda，左边显示未安装，右边远程主机显示正常。
![Uploading 1704958954217.jpg…]()
请问这是怎么回事。

**Comment by OrdinaryChen** [comment]
![1704958954217](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/1a7ec0db-bac5-43de-94dd-897c41235873)

**Comment by OrdinaryChen** [comment]
> 这是 conda 在不同终端初始化的问题，和 MobaXterm 这个工具是没有关系的 详见 conda init --help 和网上的其他问答。

我试了一下  和python相关的conda  pip 等都不行  
![1704961043554](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/8cea62cd-b408-4e8b-9e4b-6aa86fe73f4a)
真的只是conda引起的这个问题而不是进的系统是错的吗  如果是那大神有相关的资料可以让我参考下吗

**Comment by OrdinaryChen** [comment]
> 这是 conda 在不同终端初始化的问题，和 MobaXterm 这个工具是没有关系的 详见 conda init --help 和网上的其他问答。


![1704961043554](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/ad3e6bae-6e97-424f-b207-f08b1bb9a74c)

**Comment by RipplePiam** [comment]
> 而且我看别人的教程ssh连接后都不会有 "Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)
> 
> * Documentation:  https://help.ubuntu.com
> * Management:     https://landscape.canonical.com
> * Support:        https://ubuntu.com/advantage
>   This system has been minimized by removing packages and content that are
>   not required on a system that users do not log into."
> 
> 这一坨文字 我猜想是不是他远程连接有什么特殊的机制让他用了一个Ubuntu 18.04.5 LTS的命令

1. 这是你 WSL 这个 Linux 系统是 Ubuntu, 这一坨是它的 SSH 欢迎标语，默认都有的，系统可以看 cat /proc/version；
2. 用 SSH 终端连接一般是 /bin/bash 终端，右边是 powershell，在 conda init shells 里归属不同分类；
3. 至于为什么右边可以用，建议 which python(conda、pip) 确认下可执行文件路径是你本地电脑还是远程的；
4. 总之是和环境变量相关的问题，与 MobaXterm 工具本身有关联的相关的设置项在 MobaXterm配置》终端》本地 shell 设置》使用 Windows PATH；

**Comment by RipplePiam** [comment]
> 真的只是conda引起的这个问题而不是进的系统是错的吗

1. 你只有直接在标签页新建 Zsh/Bash shell 终端时，才会进入 MobaXterm 自带的 Cygwin 系统，查看版本 cygcheck -c cygwin
2. 其他终端进入的是对应的系统；

**Comment by OrdinaryChen** [comment]
> > 真的只是conda引起的这个问题而不是进的系统是错的吗
> 
>     1. 你只有直接在标签页新建 Zsh/Bash shell 终端时，才会进入 MobaXterm 自带的 Cygwin 系统，查看版本 cygcheck -c cygwin
> 
>     2. 其他终端进入的是对应的系统；

我基本理解了  也就是说mobaxterm 在zsh和bash shell时候才用了cygwin系统  让我们在交互时候更方便，而ssh的时候就是直连不通过中间的系统交互，应该是这么理解没错吧。我刚才cat /proc/version对比后，ssh里外显示的确实是我同一个docker系统。
那我应该怎么处理呢  我查到一些资料 但是似乎不太正确 https://stackoverflow.com/questions/56361590/how-to-run-a-local-conda-environment-through-an-ssh-connection

**Comment by OrdinaryChen** [comment]
> > 真的只是conda引起的这个问题而不是进的系统是错的吗
> 
>     1. 你只有直接在标签页新建 Zsh/Bash shell 终端时，才会进入 MobaXterm 自带的 Cygwin 系统，查看版本 cygcheck -c cygwin
> 
>     2. 其他终端进入的是对应的系统；

![1704963759915](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/1076dcb0-3ac8-45f1-b4a3-17e70fae6b93)
我对比了两边的$PATH是不一样的，是修改这个让ssh里和服务器一样就好了吗。我在MOBAXterm的设置里看过了  使用windows默认就是开着的。现在咋操作啊大佬  成功的话我写个完整的东西然后发这里再close掉

**Comment by OrdinaryChen** [comment]
问题已经解决了，解决方法是在远程的原始机器上输入conda init，然后输入source ~/.bashrc，这时候docker的容器前面会多一个（base）最后重新连接一下ssh会话就可以了，这时候conda python和pip全部都便正常了。大佬可以补充下这是什么原理，为啥conda在ssh前需要初始化一下，ssh难道不是直接把信号发给docker容器吗，然后把返回的信息打印在ssh窗口上吗，为啥会这样，不过感谢大佬的回答。

**Comment by OrdinaryChen** [comment]
问题已经解决了，解决方法是在远程的原始机器上输入conda init，然后输入source ~/.bashrc，这时候docker的容器前面会多一个（base）最后重新连接一下ssh会话就可以了，这时候conda python和pip全部都便正常了。大佬可以补充下这是什么原理，为啥conda在ssh前需要初始化一下，ssh难道不是直接把信号发给docker容器吗，然后把返回的信息打印在ssh窗口上吗，为啥会这样，不过感谢大佬的回答。

**Comment by OrdinaryChen** [comment]
> > 真的只是conda引起的这个问题而不是进的系统是错的吗
> 
>     1. 你只有直接在标签页新建 Zsh/Bash shell 终端时，才会进入 MobaXterm 自带的 Cygwin 系统，查看版本 cygcheck -c cygwin
> 
>     2. 其他终端进入的是对应的系统；

感谢大佬   你不鸟我 跟我说conda的初始化问题  我估计这辈子也想不到了  感谢感谢

**Comment by RipplePiam** [comment]
哈哈吓我一跳，看成我不理你了 😄 (不用改了，没关系的)
那就主要是环境变量问题。
那你可以试试把相关路径加入到环境变量里去
```bash
nano ~/.bashrc

export PATH="/opt/conda/bin:$PATH"
export ...
...

# 保存退出, source ~/.bashrc
```
我也只是抛砖引玉罢了，问题是你通过自己的实践解决的
