### ISSUE TITLE
工具栏设置自定义按钮后全都不见了

### ISSUE THREAD

**Issue by woliuguojian** [RipplePiam/MobaXterm-Chinese-Simplified#5]
![image](https://user-images.githubusercontent.com/34774269/188431214-1cf99c96-bef2-484b-8082-3b9e9184bfc2.png)
![image](https://user-images.githubusercontent.com/34774269/188431412-b589e71f-91e2-4ecb-a49d-f7f86b2f9e83.png)
原版正常

**Comment by RipplePiam** [comment]
这是配置文件冲突引起的问题。
解决方法：备份配置文件，然后关闭程序，并将程序根目录中的配置文件 `MobaXterm.ini` 删除，重新打开程序即可解决。

**Comment by wangsvip** [comment]
安装程序的根目录没有 MobaXterm.ini 这个文件

**Comment by RipplePiam** [comment]
> 安装程序的根目录没有 MobaXterm.ini 这个文件, 直接点击重置配置就可以了

嗯。如果是有这个配置文件的话，注意重置操作是单次起作用，重新打开软件还是会丢失工具栏图标；
因此存在配置文件时，需要删除才不会有这个问题。

**Comment by RipplePiam** [comment]
bugfixed. see #6
