### ISSUE TITLE
右键菜单没有汉化

### ISSUE THREAD

**Issue by ldw-hub** [RipplePiam/MobaXterm-Chinese-Simplified#56]
右键菜单没有汉化

**Comment by Yangmiss666** [comment]
感谢作者，希望更新下右键汉化

**Comment by success-crypto** [comment]
![20240725101243](https://github.com/user-attachments/assets/348e0dd6-9b87-41b4-b678-7c3f3ed95066)
作者说明不涉及反编译，所以右键菜单无法汉化
