### ISSUE TITLE
界面中文变问号

### ISSUE THREAD

**Issue by OrdinaryChen** [RipplePiam/MobaXterm-Chinese-Simplified#59]
我的mobaxterm界面上所有的中文都会变成问号，但是命令行窗口的中文确实正常的。
![1719212978164](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/bdb9c96f-27fb-4e4c-b1d1-a8e62a62a2fc)

我已经将我windows的语言环境设置为utf-8了，还是没有用
![1719213412599](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31204657/ff34ca16-62b2-4611-890c-f62a2f46c244)

**Comment by KittyChen913** [comment]
我在 w11 安裝 MobaXterm_Portable_v23.0_zh-CN-beta.1 也會造成中文變問號，但是我在 w10 電腦安裝同個版本就正常
<img width="488" alt="image" src="https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/assets/31272686/a2ef5d02-2e59-4e48-842c-6220ed2b84d3">

**Comment by zzzgno5** [comment]
请问解决了嘛？我也是这样

**Comment by zzzgno5** [comment]
已解决
https://www.cnblogs.com/sdlz/p/17460382.html
