### ISSUE TITLE
当ssh一个无法ping通的ip时，MobaXterm会出现挂死无响应

### ISSUE THREAD

**Issue by pengjiangchao** [RipplePiam/MobaXterm-Chinese-Simplified#68]
![image](https://github.com/user-attachments/assets/83744788-c182-43d8-bce0-c6ee917fc50a)

**Comment by pengjiangchao** [comment]
step1: ssh一个无法ping通的ip
step2: 不关闭ssh会话的前提下，重新新建会话

**Comment by RipplePiam** [comment]
无法复现
ssh 会等待连接超时后终止会话
