### ISSUE TITLE
皮肤中的深色skin疑似因为汉化无法使用

### ISSUE THREAD

**Issue by sdgsgsdf** [RipplePiam/MobaXterm-Chinese-Simplified#73]
在23.0中可以正常使用
![图片](https://github.com/user-attachments/assets/fde3e8f0-604a-4409-a46d-4cd9d6a91c2a)
但最新两个版本似乎将deep汉化为深色，导致选择的时候出现如下报错，并且此时界面显示也会缺少工具栏，只能通过任务管理器关闭
![图片](https://github.com/user-attachments/assets/cac708c0-6fa6-4dad-bba4-537a62ada1c7)

**Comment by RipplePiam** [comment]
感谢反馈，现已去除该汉化，如有需要可至 Release 下载。
